export const data = [
  {
    title: 'Portfolio',
    desc: 'Portfolio – My personal platform to showcase projects, skills, and professional journey.',
    stack: [
      'Next.js',
      'TypeScript',
      'MUI Joy',
      'GSAP',
      'Swiper',
      'SCSS',
      'ESLint',
      'Prettier',
      'Jest',
      'React Testing Library',
    ],
    images: [
      '/assets/images/portfolio/portfolio/portfolio-1.jpg',
      '/assets/images/portfolio/portfolio/portfolio-2.jpg',
    ],
  },
  {
    title: '.cover',
    link: 'https://vercel.com/api/toolbar/link/dotcover-react-e.vercel.app?via=team-dashboard-project-entity&p=1&page=/',
    desc: '.cover – A platform for book cover artists to connect, showcase their work, and collaborate.',
    stack: [
      'Webpack',
      'React',
      'TypeScript',
      'React Router',
      'Tailwind CSS',
      'Biome',
      'Prettier',
      'clsx',
      'Jest',
      'React Testing Library',
    ],
    images: [
      '/assets/images/portfolio/cover/cover-1.jpg',
      '/assets/images/portfolio/cover/cover-2.jpg',
    ],
  },
  {
    title: 'Hyperrealism',
    link: 'https://vercel.com/api/toolbar/link/gallery-webpack.vercel.app?via=team-dashboard-project-entity&p=1&page=/',
    desc: 'Hyperrealism – A web app for hyperrealism artists to showcase their art and connect with others.',
    stack: [
      'Webpack',
      'React',
      'TypeScript',
      'SCSS',
      'ESLint',
      'Prettier',
      'GSAP',
      'MUI',
      'Jest',
      'React Testing Library',
    ],
    images: [
      '/assets/images/portfolio/gallery/gallery-1.jpg',
      '/assets/images/portfolio/gallery/gallery-2.jpg',
    ],
  },
  {
    title: 'Calendar',
    link: 'https://vercel.com/api/toolbar/link/calendar-omega-indol.vercel.app?via=team-dashboard-project-entity&p=1&page=/',
    desc: 'Calendar – A sleek web app to manage your schedule, events, and reminders efficiently.',
    stack: [
      'Next.js',
      'TypeScript',
      'Zustand',
      'Kinde',
      'MongoDB',
      'Mongoose',
      'Biome',
      'Jest',
      'React Testing Library',
    ],
    images: [
      '/assets/images/portfolio/calendar/cal-1.jpg',
      '/assets/images/portfolio/calendar/cal-2.jpg',
    ],
  },
  {
    title: 'PSA',
    link: 'https://vercel.com/api/toolbar/link/art-gallery-delta-three.vercel.app?via=team-dashboard-project-entity&p=1&page=/',
    desc: 'PSA – Application for viewing cultural events and activities.',
    stack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'ESLint',
      'Prettier',
      'Jest',
      'React Testing Library',
      'Docker',
    ],
    images: [
      '/assets/images/portfolio/psa/psa-1.jpg',
      '/assets/images/portfolio/psa/psa-2.jpg',
    ],
  },
  {
    title: 'MovieLib',
    link: 'https://vercel.com/api/toolbar/link/movielib-client.vercel.app?via=team-dashboard-project-entity&p=1&page=/',
    desc: 'MovieLib – A web app to discover, track, and favorite your favorite movies.',
    stack: [
      'Vite',
      'TypeScript',
      'SCSS',
      'Biome',
      'Vitest',
      'Express',
      'MongoDB',
      'Mongoose',
      'Docker',
    ],
    images: [
      '/assets/images/portfolio/movies/movies-1.jpg',
      '/assets/images/portfolio/movies/movies-2.jpg',
    ],
  },
  {
    title: 'TravelApp',
    link: 'https://vercel.com/api/toolbar/link/traval-app2-0.vercel.app?via=team-dashboard-project-entity&p=1&page=/',
    desc: 'TravelApp – A landing page for a dynamic platform to explore destinations, plan trips, and track adventures.',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    images: [
      '/assets/images/portfolio/travel/travel-1.jpg',
      '/assets/images/portfolio/travel/travel-2.jpg',
    ],
  },
  {
    title: 'CarHub',
    link: 'https://vercel.com/api/toolbar/link/carshowcase-danylo.vercel.app?via=team-dashboard-project-entity&p=1&page=/',
    desc: 'CarHub – A sleek platform to explore, compare, and track your favorite cars.',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Headless UI'],
    images: [
      '/assets/images/portfolio/cars/cars-1.jpg',
      '/assets/images/portfolio/cars/cars-2.jpg',
    ],
  },
];
